### ISSUE TITLE
Validate current checkin app features/behavior

### ISSUE THREAD

**Issue by evan10s** [HackGT/Checkin-Android#3]
- [x] Signing into to a dev vs. prod instance - #2 
- [x] Scanning QR code from registration - works
- [x] Scanning/writing to NFC tag - works but permanent badge locking could be handled better (#8)
- [x] Reading NFC tag and adding tags in checkin - currently not functional because of conversion to Kotlin in progress
- [ ] What happens on check-in scan for the following situations:

- [x] - User already checked in - doesn't seem like it errors? #10 
- [x] - Invalid user ID scanned - shows a toast
- [x] - User cannot check-in because they were rejected from event or did not accept RSVP) - this is pretty much impossible
- [x] - Unable to contact server - no error #9
- [x] - Server error / unexpected response from server - also #9
- [x] - Device NFC error/unsupported - you can't install the app if device doesn't support NFC, if NFC is disabled, NFC badges just don't scan
- [ ] - Device camera error/unsupported
